name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check Format
      run: cargo fmt --all --check
    - name: Clippy
      run: cargo clippy --all -- -D warnings
    - name: Check 
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose

permissions:
  contents: read
